language: ruby
sudo: false
rvm:
  - 2.2
jdk:
  - oraclejdk8
env:
  matrix:
    - "RAILS_VERSION=4.2.5"
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  irc: "irc.freenode.org#projecthydra"
