language: ruby
sudo: false
rvm:
  - 2.2

env:
  matrix:
    - "RAILS_VERSION=4.2.5"
    - "RAILS_VERSION=4.1.14"
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  irc: "irc.freenode.org#projecthydra"
