language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.1.8"
    - "RAILS_VERSION=4.2.3"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=4.1.8"
notifications:
  irc: "irc.freenode.org#projecthydra"
before_script:
  - jdk_switcher use oraclejdk8