language: ruby
rvm:
  - 2.1

env:
  matrix:
    - "RAILS_VERSION=4.2.0"
    - "RAILS_VERSION=4.1.8"
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  irc: "irc.freenode.org#projecthydra"
