language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2

env:
  matrix:
    - "RAILS_VERSION=4.2.4"
    - "RAILS_VERSION=4.1.13"
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  irc: "irc.freenode.org#projecthydra"
